
CREATE TABLE IF NOT EXISTS METRICS (
    id NUMBER AUTO_INCREMENT PRIMARY KEY,
    name CHAR(200),
    sales_units NUMBER,
	stock CHAR(100)
);

CREATE SEQUENCE IF NOT EXISTS METRICS_SEQ
	START WITH 1
 	INCREMENT BY 1
 	NOCACHE;